### PR TITLE
Add a lot of Sites

### LINKED ISSUE #90: Mercado Libre Issue/bug
Mercado Libre Issue (.ar)
Mercado Libre seems to change url according to _what you are doing on the website._ (Brain cells dying trying to write)
Seems like there are these prefix (prefix.mercadolibre.com) :
* home.
* producto.
* articulo.
* myaccount.
* listado.

### LINKED ISSUE #95: Add marketplace.secondlife.com
https://marketplace.secondlife.com/

Suggested on Discord.

### PR DESCRIPTION
**Pull request by qfoxb**
I'm going to be completely honest, this feels super overkill but I was bored and decided to go do this for an hour or two
- [X] Resolve #95 
- [X] Add every craigslist subdomain ([Thanks!](https://gist.github.com/jeffThompson/62fcd3540affdf194b9a))
- [X] Remove duplicate lines
- [X] Remove capital letters
- [x] Resolve #90

### CODE REVIEW

**Comment by qfoxb** [comment]
There seems to be an invalid URL somewhere in the site list, the extension does not play music on any websites

**Comment by qfoxb** [comment]
After some testing, it's not any of the mercado libre domains or the craigslist domains.

**Comment by rhld16** [comment]
That issue is unrelated to your PR as I've been able to reproduce it on the master branch

**Comment by qfoxb** [comment]
Am able to reproduce on the chrome webstore version as well

**Comment by qfoxb** [comment]
fixed branch conflicts

**Comment by qfoxb** [comment]
added 
image

**Pull request merged**
