### PR TITLE
Added Excluded Sites Feature 

### PR DESCRIPTION
**Pull request by rarDevelopment**
Added a feature to allow excluding specific sites, in case you don't want music to play on certain sites. This is via a button to exclude the current site, as well as a new options page to manually manage the list of excluded sites.

Also fixed an occasional bug that threw an error when the url wasn't a proper url

Also updated from `chrome.storage.local` to `chrome.storage.sync`, as this should allow users to sync across devices. Also, it will fall back to working like the former if the latter isn't set.

Screenshot of UI changes:

image
image

### CODE REVIEW

**Review by qfoxb — APPROVED** [review]
Works on my machine! Thanks for the error fix

**Comment by qfoxb** [comment]
Would it be better to instead have a button to disable music on a specific website and then have them saved internally?

**Comment by rarDevelopment** [comment]
> Would it be better to instead have a button to disable music on a specific website and then have them saved internally?

I think that might be nice yeah. I think displaying the list still would be helpful, so maybe I could just add a button in addition to what's been done here.

**Comment by rarDevelopment** [comment]
> Would it be better to instead have a button to disable music on a specific website and then have them saved internally?

annnnd updated 😄

**Review by qfoxb — APPROVED** [review]
Thanks for the awesome update! Works on my machine

**Comment by rarDevelopment** [comment]
Alright I updated this again to include an options page for the list of excluded sites that you can manually manage, and now the main popup just has the button (plus a button that opens said options page).

Also! I updated the extension from chrome.storage.local to chrome.storage.sync, as this should allow users to sync across devices. Also, it will fall back to working like the former if the latter isn't set. That's a bit more than I wanted to include in this PR originally but it was the suggested method on the options page documentation so I figured it made sense across the extension since it falls back if not set.

**Comment by corbindavenport** [comment]
Thanks for all this :) I'll probably end up merging the separate options page back into the popup, just because two pages that are sort of for the same thing but in two different places might be confusing.

**Pull request merged**
