### PR TITLE
Added various shopping website + musics

### PR DESCRIPTION
**Pull request by Gaerisson**
Added various shopping website (mostly french)

### CODE REVIEW

**Comment by rhld16** [comment]
Try to ensure that you aren't adding duplicates such as aliexpress.com

**Comment by Gaerisson** [comment]
> Try to ensure that you aren't adding duplicates such as aliexpress.com

oh, yeah, sorry, I will double check

**Review by qfoxb — CHANGES_REQUESTED** [review]
Please read [CONTRIBUTING.md](https://github.com/corbindavenport/wii-shop-extension/blob/master/CONTRIBUTING.md), no more music please 
The ability to add custom music may be added in the future, see #22

**Comment by corbindavenport** [comment]
Closing this because it adds more music, but I've added the sites from this PR to the main list: https://github.com/corbindavenport/wii-shop-extension/commit/1aea3944c051d468cdec562630642c44ba7a71a7

**Pull request closed without merging**
